package com.mvn.gdyh.model;

// Generated 2014-12-18 16:29:50 by Hibernate Tools 4.3.1

/**
 * TblGdyhUserInf generated by hbm2java
 */
public class TblGdyhUserInf implements java.io.Serializable {

	private String username;
	private String password;
	private String addr;

	public TblGdyhUserInf() {
	}

	public TblGdyhUserInf(String username, String password, String addr) {
		this.username = username;
		this.password = password;
		this.addr = addr;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

}
